### ISSUE TITLE
两个小建议

### ISSUE THREAD

**Issue by ciskonc** [gkovacs/rime-japanese#4]
japanese.schema.yaml 文件下
```
switches:
  - name: ascii_mode
    reset: 0
    states: [ 中文, 西文 ]
  - name: full_shape
    states: [ 半角, 全角 ]
  - name: simplification
    states: [ 漢字, 汉字 ]

```
建议在 states: [ 漢字, 汉字 ]下添加 **reset: 0**  我使用中发现，如果在日文输入法下，切换到繁体后，切换回双拼，输入会变成打繁体，而在默认是拼音是简体情况下，切换到日语输入法输入，就会变成打简体中文很蛋疼。日语输入基本上没有使用切换到简体的必要就直接设置成繁体更好。

```
switches:
  - name: ascii_mode
    reset: 0
    states: [ 中文, 西文 ]
  - name: full_shape
    states: [ 半角, 全角 ]
  - name: simplification
    states: [ 漢字, 汉字 ]
    reset: 0
```

第二个小建议是选字用上下慢慢移动到下一页很麻烦，可以添加一个翻页功能
```
key_binder:
  bindings:
    #[]翻页
    - {accept: bracketleft, send: Page_Up , when: has_menu}
    - {accept: bracketright, send: Page_Down , when: has_menu}
```
