### ISSUE TITLE
how to input ー？

### ISSUE THREAD

**Issue by Freed-Wu** [gkovacs/rime-japanese#8]
For example, ノート shoulde be no-to, however, - will become page down. Is it possible to use _ to replace -?

I try:

```yaml
  key_binder/bindings/@next:
    accept: Control+minus
    send: minus
    when: always
```

can work,

```yaml
  key_binder/bindings/@next:
    accept: underscore
    send: minus
    when: always
```

cannot. However, in mobile without keyboard, ctrl is hard to be typed.

TIA!
